# $Id: acronyms.properties,v 1.1.1.1 2005-07-28 22:05:44 sina Exp $
# Acronym file used for token replacement

acro.xml: 	eXtensible Markup Language
acro.xsl:	eXtensible Stylesheet Language
acro.xslt: 	eXtensible Stylesheet Language Transformation
acro.fop: 	Formatting Objects Processor
acro.fo: 	Formatting Object
acro.xhtml: 	eXtensible Hyper Text Markup Language
acro.html: 	Hyper Text Markup Language
acro.css: 	Cascading Style Sheet
acro.rtf: 	Rich Text Format
acro.pdf: 	Portable Document Format
acro.w3c: 	World Wide Web Consortium
acro.url: 	Uniform Resource Locator
acro.cvs: 	Concurrent Version System
acro.gnu: 	GNU's Not Unix
acro.dtd: 	Document Type Definition
acro.gpl: 	GNU General Public License
acro.email: 	Electronic Mail
acro.rss: 	RDF Site Summery
acro.xinvoice:	eXtensible Invoice
acro.xwtk:	XML Website ToolKit
acro.rdf: 	Resource Description Framework
