# $Id: build.properties,v 1.1.1.1 2005-07-28 22:05:43 sina Exp $
# Build properties to build SilkPage.
# Copyright (c) 2004 MarkupWare.  All rights reserved.

temp.dir=${java.io.tmpdir}

default.encoding = UTF-8
#------------------------------------------------------------------------------
# Set filters and properties related to the applcation
#------------------------------------------------------------------------------
copyrights:		Copyright (C) 2004, 2005 MarkupWare.
copyright.holder:   	MarkupWare
copyright.year:   	2004, 2005
authors:		MarkupWare Team
product.name: 		SilkPage
product.number:		0.4.0
app.release.name:	silkpage-core
app.release.number:	0_4_0
app.release.url:	http://silkpage.markupware.com

#------------------------------------------------------------------------------
# Set the properties related to the build tree
#------------------------------------------------------------------------------
build.dir:			${temp.dir}/${app.release.name}/build
build.xsl.dir:			${build.dir}/xsl
build.cfg.dir:			${build.dir}/cfg
build.xml.dir:			${build.dir}/xml

#------------------------------------------------------------------------------
# Set the properties related to the source tree
#------------------------------------------------------------------------------
src.dir: 		.
src.share.dir:		${src.dir}/share
src.tools.dir:		${src.share.dir}/tools
src.lib.dir:		${src.share.dir}/lib
src.cfg.dir:		${src.dir}/cfg
src.img.dir:		${src.dir}/images
src.src.dir:		${src.dir}/src
src.xsl.dir:		${src.src.dir}/xsl
src.css.dir:		${src.src.dir}/css
src.schema.dir:		${src.src.dir}/schema
src.xml.dir:		${src.src.dir}/xml
src.docs.dir:		${src.xml.dir}/docs

java.lib.dir:		${src.lib.dir}/java
#------------------------------------------------------------------------------
# Set the properties related to the distribution tree
#------------------------------------------------------------------------------
dist.url:		http://silkpage.markupware.com/dist
dist.name:		${app.release.name}
dist.tag:		${app.release.name}-${app.release.number}
dist.dir: 		${temp.dir}/${app.release.name}/dist
dist.src.dir:		${dist.dir}/src
dist.share.dir:		${dist.dir}/share
dist.docs.dir:	        ${dist.dir}/docs
dist.img.dir:		${dist.dir}/images
dist.cfg.dir:		${dist.dir}/cfg
dist.css.dir:	        ${dist.src.dir}/css
dist.lang:		en

changeLog.basename:	 		changelog

usr.local.share.dir: /usr/local/share
docbook-website-zip.file: ${usr.local.share.dir}/docbook-website.zip
docbook-xsl-zip.file: ${usr.local.share.dir}/docbook-xsl.zip

#  ===========================Install Info =============================
deploy.dir:		${temp.dir}/${app.release.name}/deploy
install.endorsed.dir:	tools/web/${app.release.name}
user.local.dir:		/usr/local

# CVS.ROOT 
cvs.authentication:     pserver
cvs.path:               /home/cvs/root
cvs.host:               localhost
cvs.passfile:           .cvspass
cvs.root:               :${cvs.authentication}:${user.name}@${cvs.host}:${cvs.path}
